=== Hannysia/xml/Lab5_Knysh_Anna/xml/forumSchema.dtd
<!ELEMENT forum (header, header_description, article*)>
<!ELEMENT header (#PCDATA)>
<!ELEMENT header_description (#PCDATA)>
<!ELEMENT article (meta_data, content, authors_image?, comments?)>
<!ELEMENT meta_data (user_date)>
<!ELEMENT user_date (user_article, user_full_information)>
<!ELEMENT user_article (article_name)>
<!ELEMENT user_full_information (username, date, time, response?)>
<!ELEMENT article_name (#PCDATA)>
<!ELEMENT username (#PCDATA)>
<!ELEMENT date (#PCDATA)>
<!ELEMENT time (#PCDATA)>
<!ELEMENT response (#PCDATA)>
<!ELEMENT content (topic, article_body)>
<!ELEMENT topic (#PCDATA)>
<!ELEMENT article_body (#PCDATA)>
<!ELEMENT authors_image (#PCDATA)>
<!ELEMENT comments (comment*)>
<!ELEMENT comment (commentator_data, authors_image?)>
<!ELEMENT commentator_data (user_article, user_full_information)>

=== Hannysia/xml/Lab5_Knysh_Anna/xml/forum.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="forumStyle.xsl"?>
<!-- <!DOCTYPE forum SYSTEM "forumSchema.dtd"> -->

<forum xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.example.com/forum forumSchema.xsd">      

    <header>Студентський форум</header>
    <header_subject>Функціональне програмування</header_subject>

    <article category="Functional Programming? Don`t Even Bother, It`s a Silly Toy">
        <meta_data>
            <user_date>
                <user_article>
                    <article_name>"Між сатирою та реальністю: критичний погляд на функціональне програмування"</article_name>
                </user_article>
                <user_full_information>
                    <username>Данило К.</username>
                    <date>середа 27 вересня 2023</date>
                    <time>19:24 PM</time>
                </user_full_information>
            </user_date>
        </meta_data>


        <content>
            <topic>Між сатирою та реальністю: критичний погляд на функціональне програмування</topic>
            <article_body>Вітаю усіх! Дякую за те, що почали читати мій відгук щодо статті Іллі Суздальницького з "Better Programming" на тему функціонального програмування. Сподіваюсь на будь-який фідбек з вашої сторони щодо моєї думки.
                            Спочатку читаючи текст, мене дещо шокувала категоричність автора щодо відкидання функціонального програмування. Проте, до кінця статті стало зрозуміло, що це сатира. І я вдячний автору за цю примітку, адже новачкам у галузі дійсно важливо розуміти, що не варто сліпо вірити всьому, що пишуть в інтернеті.

                            Часто в інтернет-дискусіях можна побачити жваві сперечання стосовно того, який підхід до програмування є кращим — функціональний чи об'єктно-орієнтований. Ілля в своїй статті дотепно висміяв обидва підходи, але насправді обидва з них мають своє місце у світі програмування. Функціональне програмування, з його акцентом на незмінність та чисті функції, може пропонувати вирішення для складних проблем, зокрема в області паралелізму та конкуренції.

                            З іншого боку, об'єктно-орієнтований підхід, який акцентується на створенні моделей реального світу через об'єкти та їх взаємодію, може бути дуже ефективним для побудови великих та складних систем. Як наголосив Суздальницький, переускладнені "enterprise-grade" підходи можуть виглядати комічно, але в деяких контекстах вони можуть бути абсолютно виправданими.

                            Стаття Іллі підкреслює важливість полягає не в тому, який підхід "кращий", а в тому, який підхід найбільш підходить для конкретної задачі або проекту. Розробник має змогу вибирати з різноманітних інструментів у своєму арсеналі, а від його вибору залежить успіх проекту. Об'єктно-орієнтоване та функціональне програмування — лише два з багатьох інструментів, які можуть допомогти розробнику досягти своєї мети.

                            Ілля в своїй статті намагається висвітлити проблему переускладнення в програмуванні, прикладом чого є "FizzBuzzEnterpriseEdition". Надто часто розробники прагнуть демонструвати свою експертизу через складні архітектурні рішення, навіть коли можна обійтися простішими методами. Це може призвести до непотрібної складності і збільшення кількості потенційних помилок у коді.

                            Проте, під час читання статті, мене особисто непокоїла думка про те, що деякі читачі можуть сприймати іронічні коментарі Іллі дослівно, не здогадуючись про сатиричний характер матеріалу. В інформаційному суспільстві, де іноді не вистачає часу для глибокого аналізу матеріалу, деякі можуть просто не розібратися в тонкощах авторського стилю.

                            Сатира — це потужний інструмент висміювання і критики, але важливо пам'ятати, що не завжди всі розуміють її правильно. Це особливо актуально для новачків у галузі програмування, які тільки починають знайомитися з різними підходами та парадигмами. Для них важливо не тільки вчитися, але й вміти відрізняти справжню інформацію від жартів.

                            Хочу завершити своєю вдячністю автору за цю статтю. Вона нагадала мені про важливість критичного мислення в галузі програмування і про те, що завжди варто шукати більше джерел інформації перед тим, як приймати будь-які висновки.
            </article_body>
        </content>



        <authors_image>../img/Danylo_K.png</authors_image>


        <comments>
            <comment>
                <commentator_data>
                    <user_article>
                        <to_article>"Між сатирою та реальністю: критичний погляд на функціональне програмування"</to_article>
                    </user_article>
                    <user_full_information>
                        <username>Вероніка В.</username>
                        <date>середа 27 вересня 2023</date>
                        <time>20:56 PM</time>
                        <response>
                            Хочу подякувати Данилу за перший абзац, адже від надихає написати відгук, це відмінна риса, тому її варто підкреслити.

                            Оцінюючи основний матеріал, мушу визнати, що автором порушено важливе питання надмірної сатиричності Іллі. Хоча клікбейт назви й привертає увагу, але багато користувачів інтернету надто поверхньо ставляться до матеріалу, тому цілком вірогідно можуть не звернути увагу на постскриптом чи навіть не дійти до нього. Фанати ООП погодяться з автором з перших сторінок, а прихильники функціонального підходу - обуряться та якнайшвидше закриють, аби не заглиблюватися в той "бруд". Данило правильно зазначає наскільки важливе критичне мислення в сьогоденні, додам, що це стосується не тільки програмування, а й будь-якої сфери життя. Тільки обираючи шлях споглядати та міркувати, можна побудувати незалежний світогляд, а думки інших не завжди треба сприймати на віру, навіть якщо це ваша найближча людина.

                            Автор змусив це пригадати, що однозначно є перевагою статті.
                        </response>
                    </user_full_information>
                </commentator_data>

                <authors_image>../img/Veronika_V.png</authors_image>

            </comment>
            <comment>
                <commentator_data>
                    <user_article>
                        <to_article>"Між сатирою та реальністю: критичний погляд на функціональне програмування"</to_article>
                    </user_article>
                    <user_full_information>
                        <username>Данило К.</username>
                        <date>середа 27 вересня 2023</date>
                        <time>21:58 PM</time>
                        <response>Превелике дякую за фідбек!</response>
                    </user_full_information>
                </commentator_data>

                <authors_image>../img/Danylo_K.png</authors_image>
            </comment>

            <comment>
                <commentator_data>
                    <user_article>
                        <to_article>"Між сатирою та реальністю: критичний погляд на функціональне програмування"</to_article>
                    </user_article>
                    <user_full_information>
                        <username>Софія Л.</username>
                        <date>середа 27 вересня 2023</date>
                        <time>22:08 PM</time>
                        <response>Дякую, що цей відгук легко читати, я розумію думки та почуття з приводу статті, та бачу, що Данило робив свій аналіз при її написанні, що також є приємним

                                Мені подобається як він висловив думку з приводу з приводу статті, виділивши найголовніше. Я згодна, що деякі новачки не могли зрозуміти іроніі Іллі, адже я й сама була впевнена, що це іронія усього лише на 90%)

                                Вважаю цю статтю унікальною в тому як Данило аналізує контекст перепалок, який підштовхнув Іллю написати статтю, а також взаємодію інших читачів, які могли не мислити критично, з цією ж статтєю

                                Дякую, Данило, за відгук, а мені приємно було писати фідбек!)
                        </response>
                    </user_full_information>
                </commentator_data>

                <authors_image>../img/Sophia_L.png</authors_image>
            </comment>


            <comment>
                <commentator_data>
                    <user_article>
                        <to_article>"Між сатирою та реальністю: критичний погляд на функціональне програмування"</to_article>
                    </user_article>
                    <user_full_information>
                        <username>Данило К.</username>
                        <date>середа 27 вересня 2023</date>
                        <time>22:19 PM</time>
                        <response>Дякую за твій фідбек, гріє душу, що ти також розділяєш мою думку!)</response>
                    </user_full_information>
                </commentator_data>

                <authors_image>../img/Danylo_K.png</authors_image>
            </comment>


            <comment>
                <commentator_data>
                    <user_article>
                        <to_article>"Між сатирою та реальністю: критичний погляд на функціональне програмування"</to_article>
                    </user_article>
                    <user_full_information>
                        <username>Вероніка В.</username>
                        <date>середа 27 вересня 2023</date>
                        <time>23:04 PM</time>
                        <response>
